/*****************************************
* File: DailyLeadProcessorTest
* Author: Mathew Ruff, Sierra-Cedar
* Description: Unit Tests for 
******************************************/
@IsTest
private class DailyLeadProcessorTest {
    static testMethod void testBehavior() {
        // Arrange


        // Act 
        Test.startTest();

        Test.stopTest();

        // Assert
        System.assert(true);
    }
}